controllers/BookController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Book;
use app\models\BookSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BookController implements the CRUD actions for Book model.
 */
class BookController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Book models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BookSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Book model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Book model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Book();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Book model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Book model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Book model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Book the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Book::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'O bibliotece';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        Staramy się zapewnić jak największą ilość książek i dopracować system, żeby czytanie i wypożyczanie książek było jak najprostsze.
    </p>

</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Kontakt';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Dziękujemy za kontakt. Odpowiemy najszybciej jak to możliwe.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            Jeśli masz jakieś pytania, proszę wypełnij odpowiednie pola i skontaktuj się z nami.
            Dziękujemy
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Wyślij', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
use app\models\Book;
use app\models\Order;
use app\models\Category;
use yii\helpers\Url;

$this->title = 'Biblioteka';
$bestOrders = Order::getBestOrdered();
$categories = Category::find()->all();

$page = (isset($_GET['page']) ? $_GET['page'] : 0);

$search = (isset($_GET['search']) ? $_GET['search'] : false);
$books = Book::show($page, $search);
?>
<div class="site-index">

    <!-- <div class="jumbotron">
        <h1>Witamy na stronie biblioteki!</h1>
    </div> -->

    <div class="body-content">

        <div class="row">
            <div class="col-xs-12">
                <form class="pull-right" action="index.php?r=site&search">
                    <label>Wyszukaj książkę
                        <input name="search" type="text" value="<?php echo isset($_GET['search']) ? $_GET['search'] : '' ?>">
                    </label>
                    <input type="submit" value="Szukaj">
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <h2>Nowości</h2>

                <div class="col-xs-12">
                    <?php foreach($books AS $book){ ?>
                    <div class="book-container">
                        <?php if($book->cover){ ?><img class="book-cover" src="<?php echo $book->cover ?>"><?php } ?>
                        <div class="book-short-desc">
                            <b>Tytuł</b>: <?php echo $book->title ?><br/>
                            <b>Kategorie</b>: <?php echo $book->category ?><br/>
                            <b>Opis</b> <?php echo substr($book->description,0,150).'...' ?><br/>
                            <a href="<?php echo Url::to(['book/view', 'id' => $book->id])?>" class="btn btn-xs btn-info">Przejdź</a>
                        </div>
                    </div>
                    <hr>
                    <?php } ?>

                </div>

                <div class="col-xs-12">
                    <?php if($page > 0){ ?>
                        <a href="index.php?page=<?= $page-1 ?>" class="btn btn-sm btn-default pull-left">Poprzednie</a> 
                    <?php } ?>

                    <?php if(count($books) >= Book::$bookOffset){ ?>
                        <a href="index.php?page=<?= $page+1 ?>" class="btn btn-sm btn-default pull-right">Kolejne</a>
                    <?php } ?>
                </div>
                
            </div>
        </div>

       <!--  <div class="row">
            <div class="col-xs-12">
                <h2>Nowości</h2>

                <div class="col-xs-12">
                    <?php foreach($books AS $book){ ?>
                    <div class="book-container">
                        <?php if($book->cover){ ?><img class="book-cover" src="<?php echo $book->cover ?>"><?php } ?>
                        <div class="book-short-desc">
                            <b><?php echo $book->title ?></b><br/>
                            <?php echo substr($book->description,0,150).'...' ?>
                            <a href="<?php echo Url::to(['book/view', 'id' => $book->id])?>">zobacz więcej</a>
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <h2>Najczęściej wypożyczane</h2>
                <?php foreach($bestOrders AS $bestOrder){ ?>
                    <div class="book-container">
                        <?php if($bestOrder->cover){ ?><img class="book-cover" src="<?php echo $book->cover ?>"><?php } ?>
                        <div class="book-short-desc">
                            <b><?php echo $bestOrder->title ?></b><br/>
                            <?php echo substr($bestOrder->description,0,150).'...' ?>
                            <a href="<?php echo Url::to(['book/view', 'id' => $bestOrder->id])?>">zobacz więcej</a>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>


        <div class="row">
            <div class="col-xs-12">
                <h2>Kategorie</h2>
                <?php foreach($categories AS $category){ ?>
                    <div class="book-container">
                        <div class="book-short-desc">
                            <b><?php echo $category->name.' ('.$category->count.')' ?></b><br/>
                            <a href="<?php echo Url::to(['category/view', 'id' => $category->id])?>">zobacz więcej</a>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div> -->

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Logowanie';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Uzupełnij dane, aby się zalogować:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Logowanie', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        Możesz zalogować się na konto administratora <strong>admin/admin</strong> albo użytkownika <strong>demo/demo</strong>.<br>
    </div>
</div>

views/site/search.php
<?php
echo '213';